theme: jekyll-theme-slate
title: [Aidan Boland]
github:
  zip_url: http://github.aboland.ie/download.zip
  another_url: another value



projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true


social_media:
  twitter: AidoBo
  # linkedin: your_username
  # medium: @your_username

